{"event": "verbose", "uuid": "43e802dd-7526-426c-b58d-290bcb14f3f3", "counter": 11, "stdout": "\u001b[0;31mThe error appears to be in '/home/dpupo/ansible-runner/project/test.yml': line 4, column 7, but may\u001b[0m", "start_line": 10, "end_line": 11, "runner_ident": "9d8571d8-0420-4b74-b982-fec36fbfd48c", "created": "2021-10-08T20:50:15.277667"}